services:
  lok8:
    container_name: lok8
    build:
      context: .
      target: development
    environment:
      KUBECONFIG: /.kube/config.yaml
      GLOBAL_MODE: false
    volumes:
      - ./package.json:/usr/app/package.json
      - ./src:/usr/app/src
      - ./.kube/config.yaml:/.kube/config.yaml
    ports:
      - "9223:9223"
    expose:
      - "9223"
